format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "bold purple"

[git_status]
style = "bold red"

[cmd_duration]
min_time = 500
format = " took [$duration](bold yellow)"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
